### PR TITLE
Revert "Feature/html updates"

### PR DESCRIPTION
**Pull request by EduOceans**
Reverts mannyigho/foto-music#18

Hi @mannyigho ,

We shouldn't be merging to main if the rest of us haven't reviewed the pull request. 

Could you explain what you're trying to do with this code?

I'm reverting the change and waiting for your approval to merge it.

### CODE REVIEW

**Comment by mannyigho** [comment]
I wanted to show a second API for us to use, that is why I did the merge late last night as I know everyone will be asleep

**Comment by mannyigho** [comment]
Kindly go ahead and merge, what I did was not directly on our ongoing project because I created 2 separate files, indext2.html and script2.js to work with

**Comment by EduOceans** [comment]
> I wanted to show a second API for us to use, that is why I did the merge late last night as I know everyone will be asleep

That's alright we can review when we wake up ;) 

Also, if you have added any extra functionality you can reuse the existing files and open a PR that adds this new implementation. There's no need to add extra files

**Comment by mannyigho** [comment]
Hi
[@eduardo](https://ukvirtfept112-jnk4207.slack.com/team/U068BL2N4PJ)
, what I merged last night was 2 different files I created, script2.js and index2.html to test the second API i was able to lay my hands on. It has no directly link with the files we are working on i.e. index.html and script.js. If you look at the link https://mannyigho.github.io/foto-music/index2.html you would see what I merged last night, just a duplicate of what we are trying to do but it has no direct connection with our project files

**Pull request merged**
